name: kansler
description: "Канслер - Все для офиса,Канцтовары,Техника,Deli torg,Signum,Grand trading"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.5+57

environment:
  sdk: '>=3.3.4 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2

  # Network
  dio: ^5.4.3+1
  dio_smart_retry: ^5.0.0

  # Logger
  logger: ^2.2.0

  # Data
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # DI
  get_it: ^7.6.8
  injectable: ^2.4.1

  # Functional programming thingies
  dartz: ^0.10.1

  # Navigation
  auto_route: ^8.0.3

  device_info_plus: ^10.1.0
  unique_identifier: ^0.3.0

  flutter_bloc: ^8.1.5
  hooked_bloc: ^1.5.0
  flutter_hooks: ^0.20.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  mockito: ^5.4.4

  easy_localization: ^3.0.7

  fluttertoast: ^8.2.8
  skeletonizer: ^1.3.0

  smart_auth: ^2.0.0
  pinput: ^5.0.0
  sticky_headers: ^0.3.0+2
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.5.0
  collection: ^1.18.0

  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  location: ^7.0.0

  mobile_scanner: ^5.1.1
  permission_handler: ^11.3.1
  # firebase_crashlytics: ^4.0.0
  firebase_core: 3.3.0
  firebase_messaging: 15.0.4
  flutter_local_notifications: ^17.2.2
  change_app_package_name: ^1.3.0
  image_network: ^2.5.6
  cached_network_image: 3.3.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_multi_formatter: ^2.13.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.0
  new_version_plus: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0

  # Freezed
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Hive generator
  hive_generator: ^2.0.1
  path_provider_platform_interface: ^2.1.2


flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/fonts/
      - assets/locale/
      - assets/illustrations/
      - assets/images/

  fonts:
    - family: KazeIcons
      fonts:
        - asset: assets/fonts/KazeIcons.ttf
