// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdsOdpt2jDRsnF613PTD_prwa4EOeJIKA',
    appId: '1:565484475257:web:7595b557a60ccb729c15a8',
    messagingSenderId: '565484475257',
    projectId: 'kansler-2c29d',
    authDomain: 'kansler-2c29d.firebaseapp.com',
    storageBucket: 'kansler-2c29d.appspot.com',
    measurementId: 'G-LBS73BDDW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5ogSFeNJ3jvhJYzVr02Ozv1d9p41Zdk',
    appId: '1:565484475257:android:ef2be1f623e859389c15a8',
    messagingSenderId: '565484475257',
    projectId: 'kansler-2c29d',
    storageBucket: 'kansler-2c29d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCreMdOgTqCj9eydkcFHF9gh9TGohPTcsc',
    appId: '1:565484475257:ios:448354255beaa82f9c15a8',
    messagingSenderId: '565484475257',
    projectId: 'kansler-2c29d',
    storageBucket: 'kansler-2c29d.appspot.com',
    iosBundleId: 'uz.kansler.app',
  );

}